server:
  port: 8081 #8181

spring:
  application:
    name: web-home
  thymeleaf:
    prefix: classpath:/templates/  #配置前缀
    cache: false  #是否开启缓存,避免改了模板还要重启服务器
    mode: HTML5
    suffix: .html   #配置后缀
    encoding: UTF-8
    content-type: text/html

eureka:
  client:
    registerWithEureka: false  #表示是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故而设置为false
    fetchRegistry:  true  #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设置为false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，多个地址可用，用，分割
  instance:
    hostname: web-home  #IP地址
    prefer-ip-address: true  #不使用主机名来定义注册中心的地址，而使用IP地址的形式，如果设置了eureka.instance.ip-address 属性，则使用该属性配置的IP，否则自动获取除环路IP外的第一个IP地址
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}  #注册名默认是“IP名:应用名:应用端口名”
