server:
  port: 8761 #8761

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost #可以自定义外部接口调用时，对应的value: @FeignClient(value = "order-home-server")
    prefer-ip-address: true  #不使用主机名来定义注册中心的地址，而使用IP地址的形式，如果设置了eureka.instance.ip-address 属性，则使用该属性配置的IP，否则自动获取除环路IP外的第一个IP地址
    instance-id: ${spring.application.name}:${spring.application.instance_id}:${server.port}
  client:
    registerWithEureka: false  #表示是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故而设置为false
    fetchRegistry:  false  #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设置为false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，多个地址可用，用，分割
  server:
    enable-self-preservation: false  #关闭注册中心的保护机制，Eureka 会统计15分钟之内心跳失败的比例低于85%将会触发保护机制，不剔除服务提供者，如果关闭服务注册中心将不可用的实例正确剔除
    eviction-interval-timer-in-ms: 60000   #清理间隔（单位毫秒，默认是60*1000）
