server:
  port: 8082 #8182

spring:
  application:
    name: order-home
eureka:
  instance:
    hostname: order-home-server #可以自定义外部接口调用时，对应的value: @FeignClient(value = "order-home-server")
  client:
    registerWithEureka: true  #表示是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故而设置为false
    fetchRegistry:  false  #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设置为false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，多个地址可用，用，分割
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    